## 다층 신경망

In [1]:
# xor_nn
# 2진 분류 : Logistic Regression
# 활성화 함수 : sigmoid 함수 사용
# two Layers of Neural Network

import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]    # (4,2)

y_data = [[0],
          [1],
          [1],
          [0]]      # (4,1)

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [2]:
# Layer 1  :  은닉층 (hidden layer)

# (4,2) * (2,2) = (4,2)
W1 = tf.Variable(tf.random.normal([2,2]), name='weight1')
b1 = tf.Variable(tf.random.normal([2]), name='bias1')

def layer1(X):
    return tf.sigmoid(tf.matmul(X,W1) + b1)

In [3]:
# Layer 2  :  출력층 (output layer)

# (4,2) * (2,1) = (4,1)
W2 = tf.Variable(tf.random.normal([2,1]), name='weight2')
b2 = tf.Variable(tf.random.normal([1]), name='bias2')

def hypothesis(X):
    return tf.sigmoid(tf.matmul(layer1(X),W2) + b2)

In [4]:
# 비용 함수 : logloss, 2진 분류 모델

def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) + (1 - y_train) * tf.math.log(1-hypothesis(x_train)))
    return cost

In [5]:
# 경사 하강법
# learning_rate(학습율)을 0.01로 설정하여 optimizer 객체를 생성
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [6]:
# 학습 시작
print('***** Start Learning!!')
for step in range(5001):
    # cost를 minimize 한다
    optimizer.minimize(cost_func,var_list=[W1,b1,W2,b2])
    
    if step % 1000 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W1:',W1.numpy(),' b1:',b1.numpy())
        
print('***** Learning Finished!!')

***** Start Learning!!
0000 cost:[ 0.70409703 ]  W1: [[-0.19030488 -0.9402918 ]
 [-0.04963874 -0.73254627]]  b1: [0.21652977 0.8206513 ]
1000 cost:[ 0.025501736 ]  W1: [[-5.0247602 -6.6669364]
 [-4.994727  -6.503276 ]]  b1: [7.5096498 2.9154744]
2000 cost:[ 0.0068961703 ]  W1: [[-5.9448414 -7.5746756]
 [-5.917538  -7.41493  ]]  b1: [8.922688 3.408214]
3000 cost:[ 0.002987126 ]  W1: [[-6.4519587 -8.081454 ]
 [-6.426094  -7.923082 ]]  b1: [9.694396  3.6749146]
4000 cost:[ 0.0015255437 ]  W1: [[-6.8228335 -8.45376  ]
 [-6.797981  -8.296075 ]]  b1: [10.256574   3.8682895]
5000 cost:[ 0.00084184005 ]  W1: [[-7.1278057 -8.760636 ]
 [-7.103756  -8.603343 ]]  b1: [10.717851  4.026454]
***** Learning Finished!!


In [9]:
# 회귀계수, weight과 bias 출력
print('weight:', W1.numpy())
print('bias:', b1.numpy())

print('weight2:', W2.numpy())
print('bias2:', b2.numpy())

weight: [[-7.1278057 -8.760636 ]
 [-7.103756  -8.603343 ]]
bias: [10.717851  4.026454]
weight2: [[ 15.241018]
 [-14.880688]]
bias2: [-7.5699553]


In [8]:
# 정확도 측정 : accuracy computation
def predict(X):
    return tf.cast(hypothesis(X) > 0.5, dtype=tf.float32)  # 예측값을 0과 1로 변환

# train 데이터로 검증
preds = predict(x_train)
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_train), dtype=tf.float32))

print("Hypothesis:\n",hypothesis(x_train).numpy(), 
      "\nPredict:\n",predict(x_train).numpy(),
      "\nAccuracy:",accuracy.numpy())

Hypothesis:
 [[9.5847249e-04]
 [9.9919164e-01]
 [9.9920160e-01]
 [8.0075860e-04]] 
Predict:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy: 1.0


## relu 사용 3층 신경망 구현
: 은닉층의 활성화함수로 'relu'가 자주 사용된다

In [33]:
# Layer 1  :  은닉층 (hidden layer)

# (4,2) * (2,5) = (4,5)
W1 = tf.Variable(tf.random.normal([2,5]), name='weight1')
b1 = tf.Variable(tf.random.normal([5]), name='bias1')

def layer1(X):
    return tf.nn.relu(tf.matmul(X,W1) + b1)   # relu 사용

In [34]:
# Layer 2  :  은닉층 (hidden layer)

# (4,5) * (5,3) = (4,3)
W2 = tf.Variable(tf.random.normal([5,3]), name='weight2')
b2 = tf.Variable(tf.random.normal([3]), name='bias2')

def layer2(X):
    return tf.nn.relu(tf.matmul(layer1(X),W2) + b2)  # relu 사용

In [35]:
# Layer 3  :  출력층 (output layer)

# (4,3) * (3,1) = (4,1)
W3 = tf.Variable(tf.random.normal([3,1]), name='weight3')
b3 = tf.Variable(tf.random.normal([1]), name='bias3')

def hypothesis(X):
    return tf.sigmoid(tf.matmul(layer2(X),W3) + b3)   # 2진 분류니까 sigmoid 사용

In [36]:
# 비용 함수 : logloss, 2진 분류 모델

def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hypothesis(x_train)) + (1 - y_train) * tf.math.log(1-hypothesis(x_train)))
    return cost

In [37]:
# 경사 하강법
# learning_rate(학습율)을 0.01로 설정하여 optimizer 객체를 생성
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [38]:
# 학습 시작
print('***** Start Learning!!')
for step in range(5001):
    # cost를 minimize 한다
    optimizer.minimize(cost_func,var_list=[W1,b1,W2,b2,W3,b3])
    
    if step % 1000 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W1:',W1.numpy(),' b1:',b1.numpy())
        
print('***** Learning Finished!!')

***** Start Learning!!
0000 cost:[ 0.746548 ]  W1: [[-0.77025205  0.9678269   0.3351241   0.33134714  1.2331858 ]
 [ 0.5865573   0.4092037   0.69737315 -1.365058   -0.8992608 ]]  b1: [-1.0226775 -1.2956215 -0.8273043 -1.2653481  1.0896453]
1000 cost:[ 0.0089238575 ]  W1: [[-0.77025205  0.8590644   0.22303277  0.33134714  2.627257  ]
 [ 0.5865573   0.30044103  0.585282   -1.365058   -2.6268322 ]]  b1: [-1.0226775 -1.4043838 -0.9393954 -1.2653481  1.1626413]
2000 cost:[ 0.0021715688 ]  W1: [[-0.77025205  0.8590644   0.22303277  0.33134714  2.8540933 ]
 [ 0.5865573   0.30044103  0.585282   -1.365058   -2.8527272 ]]  b1: [-1.0226775 -1.4043838 -0.9393954 -1.2653481  1.1524502]
3000 cost:[ 0.00088857533 ]  W1: [[-0.77025205  0.8590644   0.22303277  0.33134714  2.9796188 ]
 [ 0.5865573   0.30044103  0.585282   -1.365058   -2.9788907 ]]  b1: [-1.0226775 -1.4043838 -0.9393954 -1.2653481  1.1497401]
4000 cost:[ 0.00043612008 ]  W1: [[-0.77025205  0.8590644   0.22303277  0.33134714  3.0727408 ]


In [39]:
# 회귀계수, weight과 bias 출력
print('weight:', W1.numpy())
print('bias:', b1.numpy())

print('weight2:', W2.numpy())
print('bias2:', b2.numpy())

print('weight3:', W3.numpy())
print('bias3:', b3.numpy())

weight: [[-0.77025205  0.8590644   0.22303277  0.33134714  3.1501734 ]
 [ 0.5865573   0.30044103  0.585282   -1.365058   -3.1502235 ]]
bias: [-1.0226775 -1.4043838 -0.9393954 -1.2653481  1.1498747]
weight2: [[ 0.68929434  0.00758459 -0.3313842 ]
 [ 0.67215526 -0.12362287  0.42992517]
 [ 1.2553493  -1.4591074   0.1964497 ]
 [ 1.2258319  -0.14778678  0.644789  ]
 [-4.300522   -1.2172114  -1.0509079 ]]
bias2: [ 4.9450154  5.2303734 -1.2743692]
weight3: [[ 5.202628  ]
 [-4.3889832 ]
 [ 0.12368698]]
bias3: [7.188945]


In [40]:
# 정확도 측정 : accuracy computation
def predict(X):
    return tf.cast(hypothesis(X) > 0.5, dtype=tf.float32)  # 예측값을 0과 1로 변환

# train 데이터로 검증
preds = predict(x_train)
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_train), dtype=tf.float32))

print("Hypothesis:\n",hypothesis(x_train).numpy(), 
      "\nPredict:\n",predict(x_train).numpy(),
      "\nAccuracy:",accuracy.numpy())

Hypothesis:
 [[6.6117456e-05]
 [9.9995279e-01]
 [9.9924564e-01]
 [6.6158202e-05]] 
Predict:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy: 1.0
